services:
  db:
    image: mysql:8.0.42
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ERP_WEB
      TZ: Afria/Lagos
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password']
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
volumes:
  mysql_data:
