services:
  # Database
  db:
    platform: linux/x86_64
    image: mysql:8.0.34-debian
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yourdb
      MYSQL_PASSWORD: password
volumes:
  db_data: