services:
  mssql:
    container_name: sql-server
    user: root
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password_123#"
    ports:
      - 1433:1433
    volumes:
      - ~/docker/sql/mssql/:/var/opt/mssql/
      - ~/docker/sql/sqlserver/:/var/opt/sqlserver/