services:
  mssql:
    container_name: sql-server
    user: root
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=Password_123#"
      - "MSSQL_PID=Developer"
    ports:
      - 1433:1433
    volumes:
      - data:/var/opt/mssql
volumes:
  data:
    driver: local